use_frameworks!

platform :ios, '9.0'

target 'LSJHTextView_Example' do
  pod 'LSJHTextView', :path => '../'

  target 'LSJHTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
